const myObjects = [{
  imgUrl: '',
  imgUrlDesktop: '',
  projectTitle: 'Multi-Post Stories #1',
  projectTitleDesktop: 'Multi-Post Stories',
  tags: ['CSS', 'HTML', 'Bootstrap', 'Ruby'],
  text: ' A daily selection of privately personalized reads; no accounts or sign-ups required. has been the industrys standard dummy text ever since the 1500s, when an unknown printer took a standard dummy text.',
  liveUrl: 'https://davykn.github.io/Davis_Portfolio/',
  sourceUrl: 'https://github.com/DavyKn/Davis_Portfolio',
},
{
  imgUrl: '',
  imgUrlDesktop: '',
  projectTitle: 'Multi-Post Stories #2',
  projectTitleDesktop: 'Multi-Post Stories',
  tags: ['CSS', 'HTML', 'Bootstrap', 'Ruby'],
  text: ' A daily selection of privately personalized reads; no accounts or sign-ups required. has been the industrys standard dummy text ever since the 1500s, when an unknown printer took a standard dummy text.',
  liveUrl: 'https://davykn.github.io/Davis_Portfolio/',
  sourceUrl: 'https://github.com/DavyKn/Davis_Portfolio',
},
{
  imgUrl: '',
  imgUrlDesktop: '',
  projectTitle: 'Multi-Post Stories #3',
  projectTitleDesktop: 'Multi-Post Stories',
  tags: ['CSS', 'HTML', 'Bootstrap', 'Ruby'],
  text: ' A daily selection of privately personalized reads; no accounts or sign-ups required. has been the industrys standard dummy text ever since the 1500s, when an unknown printer took a standard dummy text.',
  liveUrl: 'https://davykn.github.io/Davis_Portfolio//',
  sourceUrl: 'https://github.com/DavyKn/Davis_Portfolio',
},
{
  imgUrl: '',
  imgUrlDesktop: '',
  projectTitle: 'Multi-Post Stories #4',
  projectTitleDesktop: 'Multi-Post Stories',
  tags: ['CSS', 'HTML', 'Bootstrap', 'Ruby'],
  text: ' A daily selection of privately personalized reads; no accounts or sign-ups required. has been the industrys standard dummy text ever since the 1500s, when an unknown printer took a standard dummy text.',
  liveUrl: 'https://davykn.github.io/Davis_Portfolio/',
  sourceUrl: 'https://github.com/DavyKn/Davis_Portfolio',
}];

export default myObjects;